version: "3"

services:
    imagemagick:
        image: dpokidov/imagemagick
        volumes:
            - .:/data
        working_dir: /data
        entrypoint: mogrify

    plantuml:
        image: miy4/plantuml
        volumes:
            - .:/data
        working_dir: /data

