@startmindmap
<style>
mindmapDiagram {
    node {
        BackgroundColor #4bc5de
        LineColor #1687a6
    }
    .current {
      BackGroundColor #ffc000
    }
    arrow {
      LineColor #1687a6
    }
}
</style>
* Introduction
** Object-oriented programming <<current>>
*** Principles
**** Encapsulation
**** Abstraction
**** Inheritance
**** Polymorphism
*** Summary
*** Issues
** Composition
*** Principles
*** Summary
*** Issues
@endmindmap
